version: '3.9'

services:
  chuyenbayhangkhong:
    image: chuyenbayhangkhong
    container_name: chuyenbay
    ports:
      - 8080:8080
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3307
    networks:
      - springboot
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql
    networks:
      - springboot

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - springboot

networks:
  springboot:
    external: true
